server:
  port: ${PORT:8002}

spring:
  application:
    name: shopping-list-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping-list

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true
    lease:
      duration: 5