server:
  port: ${PORT:8001}

spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true